---
title: "Data Analysis"
output: html_document
date: "2023-11-13"
editor_options: 
  chunk_output_type: inline
---


```{r setup, include=FALSE}

# Set your working directory
library(here)
here()

# Loading packages
library(tidyverse)
library(lubridate)
library(cowplot)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)


# Reading in the data
SurgeUptakeNitrogen <-
  read.csv(here('Data','Processed','Nitrogen_Processed.csv'), stringsAsFactors=TRUE)
```

#Need to explain uptake rate calculation
# Question 1: Does giant kelp nitrogen surge uptake vary per spring and summer season?

```{r}

Season <- SurgeUptakeNitrogen %>%
  mutate(DayReplicate = as.factor(Day_Replicate))%>%
  mutate(NewTime = as.factor(Time))


Season$Season <-factor(Season$Season, labels = c("Spring", "Summer"))
Season$Nitrogen_Types<-factor(Season$Nitrogen_Types, labels= c("Ammonium", "Nitrate", "Urea"))


NitrogenSeasonBox <- 
  ggplot(Season, aes(x = Season, y = Uptake_Rate)) +
  geom_boxplot()+
  labs(title="Nitrogen Uptake Rate by Season", x="Season", y="Nitrogen Uptake Rate (V(hr1))")

print(NitrogenSeasonBox)
ggsave(file=here('Output', 'Analysis','NitrogenSeasonBox.png'), width = 10, height = 10, units = "cm")

#BiomassSeasonBox <- 
#  ggplot(Season, aes(x = Biomass_Uptake, y = Season)) +
#  geom_boxplot()+
#  xlab("Biomass Uptake Rate")

#print(BiomassSeasonBox)


NitrogenSeasonPoint <- 
  ggplot(Season, aes(x = DayReplicate, y = Uptake_Rate, color=Season)) +
  geom_point(alpha=.6)+
  labs(title="Nitrogen Uptake Rate by Day and Season", x="Days", y="Nitrogen Uptake Rate (V(hr1))")


print(NitrogenSeasonPoint)
ggsave(file=here('Output', 'Analysis','NitrogenSeasonPoint.png'), width = 10, height = 10, units = "cm")

#BiomassSeasonPoint <- 
#  ggplot(Season, aes(x = DayReplicate, y = Biomass_Uptake, color=Season)) +
#  geom_point()+
#  xlab("Days of Study")+
#  ylab("Biomass Uptake Rate")

#print(BiomassSeasonPoint)

NitrogenSeasonBox2 <- 
  ggplot(Season, aes(x = Nitrogen_Types, y = Uptake_Rate, color=Season)) +
 geom_boxplot()+
 labs(title="Nitrogen Uptake Rate by Types and Season", x="Nitrogen Types", y="Nitrogen Uptake Rate (V(hr1))")

print(NitrogenSeasonBox2)
ggsave(file=here('Output', 'Analysis','NitrogenSeasonBox2.png'), width = 10, height = 10, units = "cm")
```
```{r Season LM}
SeasonLM <-lm(data = Season, Uptake_Rate~Season)
summary(SeasonLM)

SeasonAOV <- aov(data=Season, Uptake_Rate~Season)
summary(SeasonAOV)


NitrogenAIC <- lm(data=Season, Uptake_Rate~Season+Nitrogen_Types+NewTime)
step(NitrogenAIC)

#really for uptake duration, not season
DurationAOV <- aov(data=Season, Uptake_Rate~NewTime)
summary(DurationAOV)

TukeyHSD(DurationAOV)

#NitrogenTukey<- HSD.test(DurationAOV, "Time", group=TRUE)
#print(NitrogenTukey)
```

# Question 2: Does giant kelp nitrogen and ammonia surge uptake vary based on the amount of exposure?

```{r Q2 Exposure Length Plots}
ExposureLength <- SurgeUptakeNitrogen %>%
  mutate(Day_Replicate = as.factor(Day_Replicate))%>%
  mutate(Time = as.factor(Time))


ExposureLength$Season <-factor(Season$Season, labels = c("Spring", "Summer"))
ExposureLength$Nitrogen_Types<-factor(Season$Nitrogen_Types, labels= c("Ammonium", "Nitrate", "Urea"))


NitrogenTimeBox <- 
  ggplot(ExposureLength, aes(x = Time, y = Uptake_Rate)) +
  geom_boxplot()+
  labs(title="Nitrogen Uptake Rate by Exposure Length", x="Exposure Length (mins)", y="Nitrogen Uptake Rate (V(hr1))")

print(NitrogenTimeBox)
ggsave(file=here('Output', 'Analysis','NitrogenTimeBox.png'), width = 10, height = 10, units = "cm")

#BiomassTimeBox <- 
#  ggplot(ExposureLength, aes(x = Time, y = Biomass_Uptake) +
#  geom_boxplot()+
#  xlab("Biomass Uptake Rate")

#print(BiomassTimeBox)


NitrogenTimePointbyDay <- 
  ggplot(ExposureLength, aes(x = Day_Replicate, y = Uptake_Rate, color=Time)) +
  geom_point(alpha=.6)+
  labs(title="Nitrogen Uptake Rate by Day and Exposure Length", x="Days", y="Nitrogen Uptake Rate (V(hr1))")


print(NitrogenTimePointbyDay)
ggsave(file=here('Output', 'Analysis','NitrogenTimePointbyDay.png'), width = 10, height = 10, units = "cm")

#BiomassTimePoint <- 
#  ggplot(ExposureLength, aes(x = Day_Replicate, y = Biomass_Uptake, color=Time)) +
#  geom_point()+
#  xlab("Days of Study")+
#  ylab("Biomass Uptake Rate")

#print(BiomassTimePoint)

NitrogenTimePointbyType <- 
  ggplot(ExposureLength, aes(x = Nitrogen_Types, y = Uptake_Rate, color=Time)) +
 geom_point()+
 labs(title="Nitrogen Uptake Rate by Types and Exposure Length", x="Nitrogen Types", y="Nitrogen Uptake Rate (V(hr1))")

print(NitrogenTimePointbyType)
ggsave(file=here('Output', 'Analysis','NitrogenTimePointbyType.png'), width = 10, height = 10, units = "cm")
```
```{r Q2 Time LM}
TimeLM <-lm(data = ExposureLength, Uptake_Rate~Time)
summary(TimeLM)

TimeAOV <- aov(data=ExposureLength, Uptake_Rate~Time)
summary(TimeAOV)


TimeNitrogenAIC <- lm(data=ExposureLength, Uptake_Rate~Time+Nitrogen_Types+Season)
step(TimeNitrogenAIC)


TimeDurationAOV <- aov(data=ExposureLength, Uptake_Rate~Time)
summary(TimeDurationAOV)

TukeyHSD(TimeDurationAOV)

```

# Question 3: Does uptake vary by type of nitrogen (ammonium, nitrate, and urea)?

```{r}

# Creating a ggplot to compare uptake of various types of nitrogen

NitrogenUptaketype <- 
  ggplot(SurgeUptakeNitrogen, aes(x = Nitrogen_Types, y = Uptake_Rate)) +
  geom_boxplot() +
  labs(title="Uptake Rate by Nitrogen Type", x="Nitrogen Types", y="Nitrogen Uptake Rate (V(hr1))")
print(NitrogenUptaketype)
ggsave(file=here('Output', 'Analysis','NitrogenUptaketype.png'), width = 10, height = 10, units = "cm")
# Creating a ggplot to compare biomass uptake of various types of nitrogen

NitrogenBiomassUptake <- 
  ggplot(SurgeUptakeNitrogen, aes(x = Nitrogen_Types, y = Biomass_Uptake)) +
  geom_boxplot() +
  labs(title="Biomass Uptake Rate by Nitrogen Type", x="Nitrogen Types", y="Biomass Uptake Rate (µg/g/min)")
print(NitrogenBiomassUptake)
ggsave(file=here('Output', 'Analysis','NitrogenBiomassUptake.png'), width = 10, height = 10, units = "cm")

# Creating a ggplot to compare how nitrogen uptake varies per day per nitrogen type
NitrogenDayUptake <-
  ggplot(Season, aes(x = Nitrogen_Types, y = Uptake_Rate, color = DayReplicate)) +
  geom_jitter(alpha = 0.5) +
  scale_color_manual(values = c("#FF0000", "#BF003F", "#7F007F", "#3F00BF", "#0000FF"))+
  labs(title="Nitrogen Uptake per Day for Each Nitrogen Type", 
       x="Nitrogen Types", 
       y="Nitrogen Uptake Rate (V(hr1))", color = "Day")

# or
# NitrogenDayUptake <-
  #ggplot(SurgeUptakeNitrogen, aes(x = Day_Replicate, y = Uptake_Rate, color = Nitrogen_Types)) +
  #geom_point(alpha = 0.5) +
  #labs(title="Nitrogen Uptake per day for each type", 
      #x="Day", 
      # y="Nitrogen Uptake Rate (V(hr1))", color = "Nitrogen Types")

print(NitrogenDayUptake)
ggsave(file=here('Output', 'Analysis','NitrogenDayUptake.png'), width = 10, height = 10, units = "cm")

```

```{r Q3 LM}

NitorgenLM <-lm(data = SurgeUptakeNitrogen, Uptake_Rate~Nitrogen_Types)
summary(NitorgenLM)

NitrogenAOV <- aov(data = SurgeUptakeNitrogen, Uptake_Rate~Nitrogen_Types)
summary(NitrogenAOV)
TukeyHSD(NitrogenAOV)

NitrogenTypeAIC <- lm(data=SurgeUptakeNitrogen, Uptake_Rate~Nitrogen_Types+Season+Time)
step(NitrogenTypeAIC)


```

