---
title: "Data Exploration"
output: html_document
date: "2023-11-13"
---

# Creating library
```{r setup, include=FALSE, echo=FALSE, message=FALSE}
# Reading in the libraries 
library(tidyverse)
library(lubridate)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)

# Checking project directory
library(here)
here()

# Reading in the data
SurgeUptakeNitrogen <-read.csv(here('Data','Processed','Nitrogen_Processed.csv'), stringsAsFactors=TRUE)
NitrogenYears <-read.csv(here('Data','Processed','NitrogenYears_Processed.csv'), stringsAsFactors=TRUE)

#Create and set theme 
mytheme <- theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
theme_set(mytheme)

#Verifying data attributes
SurgeUptakeNitrogen$Time <- as.factor(SurgeUptakeNitrogen$Time)
SurgeUptakeNitrogen$Blade_Replicate <- as.factor(SurgeUptakeNitrogen$Blade_Replicate)
SurgeUptakeNitrogen$Day_Replicate <- as.factor(SurgeUptakeNitrogen$Day_Replicate)
```

# Site Locations
```{r setup, include=FALSE, echo=FALSE, message=FALSE}

# Mapping the locations of the study sites

# Creating a dataframe of the locations
Site_Name <- c("Mohawk Reef", "Arroyo Quemado Reef", "Arroyo Burro Reef")
Longitude <- c("-119.7295", "-120.11905", "-119.7445915	")
Latitude <- c("34.3940708", "34.46774988", "34.400275")

Site_information <- data.frame(Site_Name, Longitude, Latitude)

# Changing Site Name, Longitude, Latitude to factors and numerics
Site_information$Site_Name <- as.factor(Site_information$Site_Name)
Site_information$Longitude <- as.numeric(Site_information$Longitude)
Site_information$Latitude <- as.numeric(Site_information$Latitude)


# Converting the dataframe into a spatial reference frame
Surge_Reef_sf <- Site_information %>% 
  st_as_sf(coords = c('Longitude','Latitude'),
           crs=4326)

# Making a map of the study sites
Surge_Reef_Map <- mapview(Surge_Reef_sf, layer.name = 'Reef Site locations')
Surge_Reef_Map

```

# Boxplot of range and means of each component of the data set
```{r}
UptakeRateBoxbyType <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Nitrogen_Types, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Nitrogen Type")
UptakeRateBoxbyType
ggsave(file=here('Output', 'BoxDataExp','UptakeRateBoxbyType.png'), width = 10, height = 10, units = "cm")

BiomassBoxbyType <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Nitrogen_Types, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Nitrogen Type")
BiomassBoxbyType
ggsave(file=here('Output','BoxDataExp', 'BiomassBoxbyType.png'), width = 10, height = 10, units = "cm")

UptakeRateBoxbySeason <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Season, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Season")
UptakeRateBoxbySeason
ggsave(file=here('Output', 'BoxDataExp','UptakeRateBoxbySeason.png'), width = 10, height = 10, units = "cm")

BiomassBoxbySeason <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Season, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Season")
BiomassBoxbySeason
ggsave(file=here('Output','BoxDataExp', 'BiomassBoxbySeason.png'), width = 10, height = 10, units = "cm")

UptakeRateBoxbyTime <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Time, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Length of Exposure")
UptakeRateBoxbyTime
ggsave(file=here('Output','BoxDataExp', 'UptakeRateBoxbyTime.png'), width = 10, height = 10, units = "cm")

BiomassBoxbyTime <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Time, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Length of Exposure")
BiomassBoxbyTime
ggsave(file=here('Output','BoxDataExp', 'BiomassBoxbyTime.png'), width = 10, height = 10, units = "cm")

UptakeRateBoxbyDayRep <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Day_Replicate, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Day Replicate")
UptakeRateBoxbyDayRep
ggsave(file=here('Output', 'BoxDataExp','UptakeRateBoxbyDayRep.png'), width = 10, height = 10, units = "cm")

BiomassBoxbyDayRep <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Day_Replicate, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Day Replicate")
BiomassBoxbyDayRep
ggsave(file=here('Output','BoxDataExp', 'BiomassBoxbyDayRep.png'), width = 10, height = 10, units = "cm")

UptakeRateBoxbyBladeRep <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Blade_Replicate, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Blade Replicate")
UptakeRateBoxbyBladeRep
ggsave(file=here('Output','BoxDataExp', 'UptakeRateBoxbyBladeRep.png'), width = 10, height = 10, units = "cm")

BiomassBoxbyBladeRep <- ggplot(SurgeUptakeNitrogen) +
  geom_boxplot(aes(x = Blade_Replicate, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Blade Replicate")
BiomassBoxbyBladeRep
ggsave(file=here('Output', 'BoxDataExp','BiomassBoxbyBladeRep.png'), width = 10, height = 10, units = "cm")
```


# Violins of range and means of each component of the data set
```{r Violins}
UptakeRateViolinbyType <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Nitrogen_Types, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Nitrogen Type")
UptakeRateViolinbyType
ggsave(file=here('Output','ViolinDataExp', 'UptakeRateViolinbyType.png'), width = 10, height = 10, units = "cm")

BiomassViolinbyType <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Nitrogen_Types, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Nitrogen Type")
BiomassViolinbyType
ggsave(file=here('Output', 'ViolinDataExp','BiomassViolinbyType.png'), width = 10, height = 10, units = "cm")

UptakeRateViolinbySeason <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Season, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Season")
UptakeRateViolinbySeason
ggsave(file=here('Output','ViolinDataExp', 'UptakeRateViolinbySeason.png'), width = 10, height = 10, units = "cm")

BiomassViolinbySeason <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Season, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Season")
BiomassViolinbySeason
ggsave(file=here('Output','ViolinDataExp', 'BiomassViolinbySeason.png'), width = 10, height = 10, units = "cm")

UptakeRateViolinbyTime <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Time, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Length of Exposure")
UptakeRateViolinbyTime
ggsave(file=here('Output', 'ViolinDataExp','UptakeRateViolinbyTime.png'), width = 10, height = 10, units = "cm")

BiomassViolinbyTime <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Time, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Length of Exposure")
BiomassViolinbyTime
ggsave(file=here('Output', 'ViolinDataExp','BiomassViolinbyTime.png'), width = 10, height = 10, units = "cm")

UptakeRateViolinbyDayRep <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Day_Replicate, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Day Replicate")
UptakeRateViolinbyDayRep
ggsave(file=here('Output', 'ViolinDataExp','UptakeRateViolinbyDayRep.png'), width = 10, height = 10, units = "cm")

BiomassViolinbyDayRep <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Day_Replicate, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Day Replicate")
BiomassViolinbyDayRep
ggsave(file=here('Output', 'ViolinDataExp','BiomassViolinbyDayRep.png'), width = 10, height = 10, units = "cm")

UptakeRateViolinbyBladeRep <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Blade_Replicate, y = Uptake_Rate))+
  labs(title="Uptake Rate (V(hr1)) by Blade Replicate")
UptakeRateViolinbyBladeRep
ggsave(file=here('Output', 'ViolinDataExp','UptakeRateViolinbyBladeRep.png'), width = 10, height = 10, units = "cm")

BiomassViolinbyBladeRep <- ggplot(SurgeUptakeNitrogen) +
  geom_violin(aes(x = Blade_Replicate, y = Biomass_Uptake))+
  labs(title= "Biomass Uptake by Blade Replicate")
BiomassViolinbyBladeRep
ggsave(file=here('Output', 'ViolinDataExp','BiomassViolinbyBladeRep.png'), width = 10, height = 10, units = "cm")

```

#Exploring Nitrogen by Years Data
```{r}
summary(NitrogenYears)

summary(NitrogenYears$Nitrogen_Percent)

NitrogenYears_Point <- ggplot(NitrogenYears, aes(x=Year, y=Nitrogen_Percent))+
  geom_point(alpha=.5)+
  labs(title="Nitrogen Percent by Year", x="Date", y="Nitrogen Percent")

print(NitrogenYears_Point)

NitrogenYears_Box <- ggplot(NitrogenYears, aes(x=NewSites, y=Nitrogen_Percent))+
  geom_boxplot()+
  labs(title="Nitrogen Percent by Site", x="Site", y="Nitrogen Percent")

print(NitrogenYears_Box)
```

