---
title: "Trends in giant kelp nitrogen surge uptake"
author: "Erin Ansbro, Cara Kuuskvere, Tani Valdez Rivas"
date: "December 2023"
output: html_document

---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
library(here)
here()

# Load your packages
library(tidyverse)
library(lubridate)
library(cowplot)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)


# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions

As climate change related issues continue to arise throughout the world, ecosystem services have been called upon to combat disasters. Nature-based solutions have been a rising trend in recent years, and they speak to the resilience that nature made flora has embedded into their structure (Seddon, 2020). Kelp forests along the United States west coast are impacted by increasing temperatures as a result of climate change. Kelp grows quickly and can sequester a large amount of carbon, aiding in the resilience of climate-change (Hurlimann, 2019). A recent study has shown that increased nitrogen uptake by kelp can limit the effect that heat has on them. This is an interesting development because nitrogen increase in California waters is related to agriculture runoff, and eutrophication is generally seen as a negative consequence of human interference. However, in this case, it assists kelp and helps them survive increased climate-change related temperature increase (Fernández, 2020).

Interested in this recent research, data about nitrogen uptake was located in the Long-Term Ecological Research database titled “SBC LTER: Reef: Surge uptake capability in Macrocystis pyrifera in response to pulses of three different forms of nitrogen” (Cedeno, 2021). This data set looked simple enough to clean while also providing enough information for a research project. 

We are interested in trends in giant kelp nitrogen surge uptake by season and by the amount of exposure. Specific questions include:

1. Does giant kelp nitrogen and ammonia surge uptake vary per spring and summer season?
2. Does giant kelp nitrogen and ammonia surge uptake vary based on the amount of exposure?
3. Does uptake vary by type of nitrogen (ammonium, nitrate, and urea)?



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 

## Question 3:


\newpage

# Summary and Conclusions


\newpage

# References
Cedeno, T., Brzezinski, M., Miller, R., Reed, D. (2021). Santa Barbara Coastal LTER: Reef: Surge uptake capability in Macrocystis pyrifera in response to pulses of three different forms of nitrogen ver 1. Environmental Data Initiative. https://doi.org/10.6073/pasta/d079ff0e95defb71b87040f56235d755 

Fernández, P.A., Gaitán-Espitia, J.D., Leal, P.P. et al. (2020). Nitrogen sufficiency enhances thermal tolerance in habitat-forming kelp: implications for acclimation under thermal stress. Scientific Reports 10, 3186.https://doi.org/10.1038/s41598-020-60104-4

Hurlimann, S. (2019, July 4). How kelp naturally combats global climate change. Science in the News.https://sitn.hms.harvard.edu/flash/2019/how-kelp-naturally-combats-global-climate-change/  

Seddon N., Chausson A., Berry P., Girardin Cécile A. J., Smith A., Turner B. (2020). Understanding the value and limits of nature-based solutions to climate change and other global challenges. The Royal Society 375, 1794. http://doi.org/10.1098/rstb.2019.0120 

